sudo: required
services:
    - docker

before_install:
    - docker build -t docker-react-dev -f Dockerfile.dev .

scripts:
    - docker run -e CI=true docker-react-dev npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-943870043357"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY